-- Create users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role_id BIGINT REFERENCES roles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create trigger to update updated_at timestamp
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Add RLS policies
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users are viewable by authenticated users."
    ON users FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Users are insertable by authenticated users."
    ON users FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "Users are updatable by authenticated users."
    ON users FOR UPDATE
    TO authenticated
    USING (true);

CREATE POLICY "Users are deletable by authenticated users."
    ON users FOR DELETE
    TO authenticated
    USING (true);
